// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkgnjwmjvrujjreoaldo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrZ25qd21qdnJ1ampyZW9hbGRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4Nzc4MTcsImV4cCI6MjA2MjQ1MzgxN30.Z9qCMKUgqY9T0ZvOw2u4q4oXOzvNWyxonA0PMFbb0SI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);